# You can do "make SUB=blah" to make only a few, or edit here, or both
# You can also run make directly in the subdirs you want.

SUB =   lib tftp tftpd

%.build:
	$(MAKE) -C $(patsubst %.build, %, $@)

%.install:
	$(MAKE) -C $(patsubst %.install, %, $@) install

%.clean:
	$(MAKE) -C $(patsubst %.clean, %, $@) clean

%.distclean:
	$(MAKE) -C $(patsubst %.distclean, %, $@) distclean

all:      MCONFIG $(patsubst %, %.build, $(SUB))

install:  MCONFIG $(patsubst %, %.install, $(SUB))

clean:    $(patsubst %, %.clean, $(SUB))

distclean: $(patsubst %, %.distclean, $(SUB))
	rm -f MCONFIG config.status config.cache config.log config.h *~ \#*
	find . -type f \( -name \*.orig -o -name \*.rej \) | xargs -r rm -f

spotless: distclean
	rm -f configure

config:	MCONFIG

release:
	$(MAKE) configure
	$(MAKE) distclean

MCONFIG: configure MCONFIG.in config.h.in
	./configure

config.h: MCONFIG
	: Generated by side effect

configure: configure.in aclocal.m4
	autoconf
	rm -f MCONFIG config.cache config.log config.h
